gestion_tache.app_project_type.*:
  type: config_entity
  label: 'App project type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    users:
      type: mapping
      label: 'Liste des utilisateurs qui peuvent voir ce contenu'
    description:
      type: text
      label: 'description'
    user_id:
      type: integer
      label: 'Auteur of node type'